---
title: 武汉大学 语言与信息研究中心
subtitle: 武汉大学计算机学院
subtitle2: 自然语言处理实验室
homepage: http://sc.whu.edu.cn/person/minpeng
phone: 027-68775667
office: 武汉大学计算机学院A516
email: pengm@whu.edu.cn
backgrounds:
  - https://spg-picgo.oss-cn-shenzhen.aliyuncs.com/20211207185956.png?x-oss-process=style/bg
  - https://spg-picgo.oss-cn-shenzhen.aliyuncs.com/20211207190246.png?x-oss-process=style/bg
  - https://spg-picgo.oss-cn-shenzhen.aliyuncs.com/20211207205054.png?x-oss-process=style/bg
research:
  - title: 自然语言理解
    description: 主要研究方向为阅读理解、对话生成等
    icon: fa-cogs
  - title: 知识图谱
    description: 显示知识发展进程与结构关系的一系列各种不同的图形，用可视化技术描述知识资源及其载体，挖掘、分析、构建、绘制和显示知识及它们之间的相互联系
    icon: fa-cubes
papers:
  - title: TopicNet Conversation Model
    author: M.Peng, D.Chen, Q.Xie
    origin:
      International Conference on Web Information Systems Engineering. Springer
      International Publishing (WISE) （CCF C类会议）,2018,pp.483-496
    link: ""
  - title: Incorporating word embeddings into topic modeling of short texts
    author: W.Gao, M.Peng, H.Wang, Y.Zhang
    origin: Knowledge and Information Systems (KAIS) （CCF B类期刊）,2018,pp.1-23
    link: ""
  - title: Bayesian Sparse Topical Coding
    author: M.Peng, Q.Xie, H.Wang
    origin: IEEE Transactions on Knowledge & Data Engineering (TKDE) （CCF A类期刊）,2018,PP(99):1-1
    link: ""
  - title: Parallelization of Massive Textstream Compression Based on Compressed Sensing
    author: M.Peng, W.Gao, H.Wang, Y.Zhang
    origin: ACM Transactions on Information Systems (TOIS)（CCF A类期刊）,2017,Vol.36 pp.1-18
    link: ""
  - title: Neural Sparse Topical Coding
    author: Min Peng, Qianqian Xie
    origin: Meeting of the Association for Computational Linguistics (ACL)（CCF A会议）,2018
    link: ""
  - title:
      Mining Event-oriented Topics in Microblog Stream with Unsupervised Multi-view
      Hierarchical Embedding
    author: Min Peng, Jiahui Zhu, Hua Wang
    origin: ACM Transactions on Knowledge Discovery from Data(TKDD) (CCF B类期刊),2018
    link: ""
  - title: Dynamic sampling of text streams and its application in text analysis
    author: G.Tian, J.Huang, M.Peng, J.Zhu, Y.Zhang
    origin: Knowledge and Information Systems (KAIS) （CCF B类期刊）,2017,Vol.53 No.2 pp.507-531
    link: ""
  - title: Personalized app recommendation based on app permissions
    author: M.Peng, G.Zeng, Z.Sun, J.Huang
    origin: "World Wide Web: Internet and Web Information Systems (WWW) （CCF B类期刊）,2017,pp.1-16"
    link: ""
  - title: A probabilistic method for emerging topic tracking in Microblog stream
    author: J.Huang, M.Peng, H.Wang
    origin: "World Wide Web: Internet and Web Information Systems (WWW)（CCF B类期刊）,2017,Vol.20No.2 pp.325-350"
    link: ""
  - title:
      High quality information extraction and query-oriented summarization for
      automatic query-reply in social network
    author: M.Peng, B. Gao, J.Zhu, J.Huang, M. Yuan, F. Li
    origin: Expert Systems with Applications (ESWA)（CCF C类期刊）,2016,Vol.44 pp.92-101
    link: ""
  - title: Sparse Topical Coding with Sparse Groups
    author: M.Peng, Q.Xie, J.Huang
    origin:
      International Conference on Web-Age Information Management. Springer International
      Publishing (WAIM) （CCF C类会议）,2016,pp.415-426
    link: ""
  - title: "KPCA-WT: An Efficient Framework for High Quality Microblog Extraction in Time-Frequency Domain"
    author: M.Peng, X.DaI, K.Zhang, G.Zeng
    origin:
      International Conference on Web-Age Information Management. Springer International
      Publishing (WAIM) （CCF C类会议）,2016,pp.304-315
    link: ""
  - title: Improving Distant Supervision of Relation Extraction with Unsupervised Methods
    author: M.Peng, J.Huang, Z.Sun, S.Wang
    origin:
      International Conference on Web Information Systems Engineering. Springer
      International Publishing (WISE) （CCF C类会议）,2016,pp.561-568
    link: ""
  - title: "Coherent Topic Hierarchy: A Strategy for Topic Evolutionary Analysis on Microblog Feeds"
    author: J.Zhu, X. Li,M.Peng,J.Huang, T. Qian, J.Huang, J. Liu, R. Hong, P. Liu
    origin:
      International Conference on Web-Age Information Management. Springer International
      Publishing (WAIM) （CCF C类会议）,2015,pp.70-82
    link: ""
  - title:
      Topic Detection from Large Scale of Short Text Stream with High Utility Pattern
      Clustering
    author: J.Huang,M.Peng,H. Wang
    origin:
      International on Conference on Information and Knowledge Management (CIKM)
      （CCF B类会议）,2015,pp.3-10
    link: ""
  - title:
      Microblog emerging topic detection method based on Regression models and
      spectral clustering
    author: M.Peng,T. Zhang,J.Huang,J.Zhu,J.Huang
    origin: Computer Engineering, SCI,2015,pp.-
    link: ""
  - title: Stock Research Reports Classification Based on Sentiment Analysis
    author: M.Peng,Q. Wang,J.Huang, L. Zhou, X. Hu
    origin: Journal of Wuhan University(Natural Science Edition),2015, pp.124-130
    link: ""
  - title: Central Topic Model for Event-oriented Topics Mining in Microblog Stream
    author: M.Peng,J.Zhu, X. Li,J.Huang, H. Wang, Y. Zhang
    origin:
      International on Conference on Information and Knowledge Management (CIKM)
      （CCF B类会议）,2015,pp.1611-1620
    link: ""
  - title:
      High Quality Microblog Extraction Based on Kernel Principal Component Analysis
      and Wavelet Transformation
    author: M.Peng,H. Fu,J.Huang,J.Huang, J. Liu
    origin: Computer Engineering, SCI,2015,pp.-
    link: ""
  - title: Automatic Summarization of Microblogs Based on High Quality Information Extraction
    author: M.Peng,B. Gao,J.Huang, J. Liu
    origin: Computer Engineering, SCI,2015,pp.36-42
    link: ""
  - title: Mass of short Texts Clustering and Topic Extraction Based on Frequent Itemsets
    author: M.Peng, J.Huang,J.Zhu, J.Huang, J. Liu
    origin: Journal of Computer Research and Development,2015,Vol.52 No.9 pp.1941-1953
    link: ""
  - title:
      The Method of Chinese Opinion Sentence Extraction and Polarity Identification
      Based on Sentimental Elements
    author: N. Liu,Y. He,F. He,M.Peng, J. Liu
    origin: Advanced Materials Research,2013,Vol.765 No.2 pp.1406-1410
    link: ""
  - title: A New Method for Micro-blog Platform Users Classification Based on Infinitesimal-time
    author: N. Liu, Y. He, Q. Chen,M.Peng, Y. Tian
    origin: IEEE Journal of Optical and Communications Networks,2013,Vol.10 No.9 pp.2569-2579
    link: ""
  - title: Lightpath Optimization in Multi-Domain Optical Networks
    author: K. Liang,M.Peng, S. Khan, A. Rayes, N. Ghani
    origin: IEEE/OSA OFC,2013,pp.17-21
    link: ""
  - title: An Optimization Approach for Multi-Domain Optical Network Provisioning
    author: K. Liang, H. Alazemi, F. Xu, M.Peng, N. Ghani
    origin: IEEE Journal of Optical and Communications Networks,2013,Vol.5 No.12 pp.1413-1424
    link: ""
  - title: Virtual Network Reconfiguration in Optical Substrate Networks
    author: F. Gu,M.Peng,S. Khan, A. Rayes, N. Ghani
    origin: IEEE/OSA OFC,2013,pp.6-10
    link: ""
  - title: Micro-blogger influence analysis based on use feature
    author: M.Peng,J.Huang,N. Ghani,S. Sun,B. Wu,Y. He,W.Wen
    origin: Journal of Internet Technology,2013,Vol.14 No.2 pp.307-314
    link: ""
  - title: Co-Learning Ranking for Query-based Retrieval
    author: M.Peng,J.Huang,J.Zhu, L. Zhou,H. Fu, Y. He,F. Li
    origin: WISE 2013,2013,pp.468-477
    link: ""
  - title:
      High Quality Microblog Extraction based on Multiple Features Fusion and Time-Frequency
      Transformation
    author: M.Peng,J.Huang,H. Fu,J.Zhu, L. Zhou, Y. He, F. Li
    origin: WISE 2013,2013,pp.188-201
    link: ""
  - title:
      A Query Expansion Based on Sentence and Vector Integration Strategy Using
      Universal Gravitation
    author: J.Huang,C. Li,S. Sun,N. Ghani,M.Peng
    origin: Journal of Information and Computational Science,2012,Vol.19 No.7 pp.5391-5400
    link: ""
  - title: Evaluation of Post-Fault Restoration Strategies in Multi-Domain Networks
    author: F. Xu,T. Das,M.Peng,N. Ghani
    origin: Optical Switching and Networking,2012,Vol.9 No.2 pp.147-155
    link: ""
  - title: The Weighted Shortest Path Search Based on Multi-Agents in Mobile GIS Services
    author: M.Peng,N. Xiong,J. H. Park,A. V. Vasilakos,J. Zhang
    origin:
      Journal of Wireless Communications and Mobile Computing (WCMC),2012,Vol.12
      No.4 pp.302-317
    link: ""
  - title: Adaptive Scheduling for Wireless Video Transmission in High-Speed Networks
    author: Z.Wan, N. Xiong, N. Ghani,M.Peng, Athanasios V. Vasilakos, L. Zhou
    origin: IEEE INFOCOM 2011 High Speed Networks Workshop,2011,pp.180-185
    link: ""
  - title: Multi-Domain DWDM Network Provisioning For Correlated Failures
    author: M. Esmaeili,M.Peng, S. Khan, J. Finochietto, Y.Jin, N.Ghani
    origin: IEEE/OSA OFC,2011,pp.6-10
    link: ""
  - title: Multi-Failure Post-Fault Restoration in Multidomain DWDM Networks
    author: F. Xu,M.Peng, A. Rayes, N. Ghani, Ashwin A. Gumaste
    origin: IEEE/OSA OFC,2011,pp.6-10
    link: ""
  - title:
      The Web Information Extraction for Update Summarization Based on Shallow
      Parsing
    author: M.Peng,X. Ma, Y. Tian, Y. Ming, H. Long, Q. Lin
    origin: 3PGCIC,2011,pp.109-114
    link: ""
  - title: Query Expansion Based on Conceptual Word Cluster Space Graph
    author: M.Peng,Q. Lin, Y. Tian, M. Yang, Y. Xiao, B. Ni
    origin: NISS,2011,pp.128-133
    link: ""
  - title: A Query Expansion Based on Sentence and Vector Integration Strategy
    author: M.Peng,M. Yang, S. Sun, H. Long, N. Ghani, B. Ni, B. Ni
    origin: NISS,2011,pp.41-45
    link: ""
  - title: Service overlays for Ethernet LAN over SONET/SDH
    author: N. Ghania,M. Esmaeilia,H. Wub,Y. Qiaoc,R. Wangd,M.Peng, B. Ni
    origin: Optical Switching andNetworking,2010,Vol.7 No.2 pp.54-65
    link: ""
  - title: Enhanced Crankback Signaling for Multi-Domain IP/MPLS Networks
    author: M. Esmaeili,F. Xu,M.Peng,N. Ghani,A. Gumastec,J. Finochiettod
    origin: ComputerCommunications,2010,Vol.33 No.18 pp.2215-2223
    link: ""
  - title: Enhanced Crankback for Lightpath Setup in Multi-Domain Optical Networks
    author: M. Esmaeili, F. Xu, N. Ghani,C. Xie,M.Peng,Q. Liu, B. Ni
    origin: IEEE Communications Letters,2010,Vol.14 No.5 pp.480-482
    link: ""
  - title: Enhanced Crankback Signaling in Multi-Domain Optical Networks
    author: M. Esmaeili, F. Xu, N. Ghani,M.Peng, Q. Liu, B. Ni
    origin: IEEE/OSA OFC,2010, pp.21-25
    link: ""
  - title: Multi-Domain Restoration with Crankback IP/MPLS Networks
    author: F. Xu,M.Peng,M. Esmaeili,N. Ghani,A. Rayes
    origin: Optical Switching and Networking,2010,Vol.8 No.1 pp.68-78
    link: ""
  - title: Advanced crankback provisioning for multi-domain networks
    author: F. Xu,M.Peng,M. Esmaeili,N. Ghani
    origin: IEEE HPSR,2010,pp.209-214
    link: ""
  - title: Post-fault restoration in multi-domain networks with multiple failures
    author: F. Xu,M.Peng,M. Esmaeili, M. Rahnamay-Naeini, S. Khan, N. Ghani,M. Hayat
    origin: IEEE MILCOM,2010,pp.593-598
    link: ""
  - title:
      Evaluation of Post-Fault Restoration Strategies in Multi-Domain Networks
      ANTS
    author: F. Xu, T. Das,M.Peng, N. Ghani
    origin: IEEE ANTS,2010,pp.43-45
    link: ""
  - title: Enhanced Crankback Signaling for Multi-Domain Traffic Engineering
    author: F. Xu, M. Esmaeili, C. Xie, N. Ghani,M.Peng, Q. Liu
    origin: IEEE ICC,2010,pp.23-27
    link: ""
  - title: The Street View Character Recognition Based on Support Vector Machine
    author: M.Peng,J. Zhang, M. Li, Y. Hu, Z. He
    origin: AIPR,2009,pp.411-415
    link: ""
  - title:
      Wireless Service Attributes Classification and Matching Mechanism Based on
      Decision Tree
    author: "M.Peng,Laurence T. Yang, W. Zhao, N. Xiong "
    origin: AINA,2008,pp.12-17
    link: ""
students:
  - name: 李冬
    grade: 2017级博士
    photo: ""
    field: ""
    description: ""
    email: ""
  - name: 韩玮光
    grade: 2018级博士
    photo: ""
    field: ""
    description: ""
    email: ""
  - name: 刘芳
    grade: 2018级博士
    photo: ""
    field: ""
    description: ""
    email: ""
  - name: 贾旭
    grade: 2019级博士
    photo: ""
    field: ""
    description: ""
    email: ""
  - name: 徐文杰
    grade: 2020级博士
    photo: https://spg-picgo.oss-cn-shenzhen.aliyuncs.com/20211209151638.png?x-oss-process=style/student
    field: 知识图谱
    description: 山水一程好风光，三生有幸珞珈山
    email: vingerxu@whu.edu.cn
    link: https://www.jaysaligia.site
  - name: 刘奔
    grade: 2021级博士
    photo: https://spg-picgo.oss-cn-shenzhen.aliyuncs.com/20211207203753.png?x-oss-process=style/student
    field: 图神经网络
    description: ""
    email: liuben123@whu.edu.cn
  - name: 柳凯
    grade: 2021级博士
    photo: https://spg-picgo.oss-cn-shenzhen.aliyuncs.com/20211208121200.png?x-oss-process=style/student
    field: 对话生成
    description: ""
    email: zerkvii@gmail.com
  - name: 刘磊
    grade: 2022级博士
    photo: ""
    field: ""
    description: ""
    email: ""
  - name: 罗娟
    grade: 2019级硕士
    photo: https://spg-picgo.oss-cn-shenzhen.aliyuncs.com/20211208121131.png?x-oss-process=style/student
    field: 社会学 心理学
    description: ""
    email: luojuan69@whu.edu.cn
  - name: 张鼎
    grade: 2019级硕士
    photo: https://spg-picgo.oss-cn-shenzhen.aliyuncs.com/20211207172840.png?x-oss-process=style/student
    field: 服务器 容器
    description: ""
    email: 79770999@qq.com
  - name: 袁尤良
    grade: 2020级硕士
    photo: https://spg-picgo.oss-cn-shenzhen.aliyuncs.com/20211207172854.png?x-oss-process=style/student
    field: 自然语言处理
    description: 八月秋寒风怒号，卷我屋上三重茅
    email: 929499176@qq.com
  - name: 谢烁圻
    grade: 2020级硕士
    photo: https://spg-picgo.oss-cn-shenzhen.aliyuncs.com/20211207172828.png?x-oss-process=style/student
    field: 云原生开发
    description: ""
    email: xieshuoqi@126.com
  - name: 胡宇翔
    grade: 2020级硕士
    photo: ""
    field: ""
    description: ""
    email: hyxwhu@qq.com
  - name: 李嘉麒
    grade: 2020级学术硕士
    photo: https://spg-picgo.oss-cn-shenzhen.aliyuncs.com/20211207183927.png?x-oss-process=style/student
    field: ""
    description: ""
    email: luckyseven1579@gmail.com
  - name: 彭美政
    grade: 2020级硕士
    photo: ""
    field: ""
    description: ""
    email: ""
  - name: 武涵
    grade: 2021级专业硕士
    photo: https://spg-picgo.oss-cn-shenzhen.aliyuncs.com/20211209173357.png?x-oss-process=style/student
    field: "\U0001F349 \U0001F3C0 \U0001F3AE"
    description: ""
    email: ""
  - name: 杨世杰
    grade: 2021级专业硕士
    photo: https://spg-picgo.oss-cn-shenzhen.aliyuncs.com/20211209173419.png?x-oss-process=style/student
    field: "\U0001F3D3、\U0001F3AC、\U0001F4DA"
    description: ""
    email: ""
  - name: 许敏章
    grade: 2021级硕士
    photo: ""
    field: ""
    description: ""
    email: ""
  - name: 彭淼
    grade: 2021级硕士
    photo: https://spg-picgo.oss-cn-shenzhen.aliyuncs.com/20211209150755.png?x-oss-process=style/student
    field: 知识图谱
    description: Storm clouds may gather, stars may collide.
    email: ""
    link: https://gknl.github.io
  - name: 陈嘉辉
    grade: 2021级硕士
    photo: https://spg-picgo.oss-cn-shenzhen.aliyuncs.com/20211207172503.png?x-oss-process=style/student
    field: 多模态
    description: ""
    email: 810014386@qq.com
projects:
  - title: 食品安全大数据智能应用技术研究
    time: 2018.12-2021.12
    description: ""
    photo: ""
    field: ""
    email: ""
  - title: 基于无监督知识提取和多关系表示学习的自动问答关键技术研究
    time: 2018.1-2021.12
    description: 国家自然科学基金面上项目，主持
  - title: 社会网络的主题演化分析与传播趋势预测研究
    time: 2015.1-2018.12
    description: 国家自然科学基金面上项目，主持
  - title: 基于反馈式排序框架F-Rank的查询导向的更新式多文档自动摘要研究
    time: 2010.1-2013.12
    description: 国家自然科学基金面上项目，主持
  - title: 可信软件构造理论与方法研究
    time: 2012.1-2015.12
    description: 国家自然科学基金重点项目，参与
  - title: 社会网络XXX
    time: 2013.1-2013.12
    description: 国家部级技术改革项目，主持
  - title: XXX分类与挖掘系统
    time: 2013.1-2012.12
    description: 国家部级技术改革项目，主持
  - title: 面向证券行业的财经新闻与股市研报文本分析
    time: 2014.1-2016.12
    description: 横向合作，主持
  - title: 基于压缩感知的社交网络主题提取与演化分析
    time: 2013.1-2015.12
    description: 深圳市知识创新计划基础研究项目，主持
  - title: 基于P2P的网络实时流媒体平台研究与开发
    time: 2009.1-2011.12
    description: 湖北省教育厅高校产学研合作重点项目，主持
  - title: 面向中文文本信息融合的句子排序研究
    time: 2008.1-2010.12
    description: 国家自然科学基金面上项目，参与
  - title: 微博重要目标及群体分析
    time: 2011.3-2012.10
    description: 厅级科技计划项目，主持
  - title: 基于图模型的网页文本自动文摘研究与应用
    time: 2009.1-2012.12
    description: 湖北省自然科学基金项目，主持
  - title: 微博信息及目标深度挖掘
    time: 2012.7-2013.7
    description: 武汉市公安局，主持
